export declare const API_VERSION = "/api/v1";
export declare const ROUTES: {
    readonly HOME: "/";
    readonly LOGIN: "/auth/login";
    readonly REGISTER: "/auth/register";
    readonly REGISTER_CORPORATE: "/auth/register/corporate";
    readonly VERIFY_EMAIL: "/auth/verify-email";
    readonly FORGOT_PASSWORD: "/auth/forgot-password";
    readonly RESET_PASSWORD: "/auth/reset-password";
    readonly STUDENT_DASHBOARD: "/student/dashboard";
    readonly STUDENT_COURSES: "/student/courses";
    readonly STUDENT_BOOKINGS: "/student/bookings";
    readonly STUDENT_CERTIFICATES: "/student/certificates";
    readonly STUDENT_CHAT: "/student/chat";
    readonly STUDENT_ORDERS: "/student/orders";
    readonly STUDENT_PROFILE: "/student/profile";
    readonly TEACHER_DASHBOARD: "/teacher/dashboard";
    readonly TEACHER_ONBOARDING: "/teacher/onboarding";
    readonly TEACHER_COURSES: "/teacher/courses";
    readonly TEACHER_AVAILABILITY: "/teacher/availability";
    readonly TEACHER_BOOKINGS: "/teacher/bookings";
    readonly TEACHER_EARNINGS: "/teacher/earnings";
    readonly TEACHER_CHAT: "/teacher/chat";
    readonly TEACHER_PROFILE: "/teacher/profile";
    readonly ADMIN_DASHBOARD: "/admin/dashboard";
    readonly ADMIN_USERS: "/admin/users";
    readonly ADMIN_TEACHERS: "/admin/teachers";
    readonly ADMIN_CATEGORIES: "/admin/categories";
    readonly ADMIN_COURSES: "/admin/courses";
    readonly ADMIN_COMPANIES: "/admin/companies";
    readonly ADMIN_PAYMENTS: "/admin/payments";
    readonly ADMIN_PAYOUTS: "/admin/payouts";
    readonly ADMIN_ANALYTICS: "/admin/analytics";
    readonly ADMIN_AUDIT_LOGS: "/admin/audit-logs";
    readonly COMPANY_ADMIN_DASHBOARD: "/company-admin/dashboard";
    readonly EMPLOYEE_DASHBOARD: "/employee/dashboard";
};
export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
//# sourceMappingURL=routes.d.ts.map